version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: userdb
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - user-service-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  user-service:
    build: .
    ports:
      - "41615:41615"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
    networks:
      - user-service-network
    deploy:
      resources:
        limits:
          cpus: '0.50'       # Max 50% of one CPU
          memory: 512M

networks:
  user-service-network:
    driver: bridge

